# Generated by Django 2.2.13 on 2020-06-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoritem',
            name='startTime',
            field=models.CharField(max_length=10),
        ),
    ]
