# Generated by Django 2.2.13 on 2020-06-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20200630_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ArchiveImages'),
        ),
    ]
