# Generated by Django 2.2.13 on 2020-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_archive_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='photo',
            field=models.ImageField(blank=True, default='http://www.esra.ir/image/layout_set_logo?img_id=15812&t=1593447006996', null=True, upload_to='ArchiveImages'),
        ),
    ]
