# Generated by Django 2.2.13 on 2020-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_auto_20200630_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='itemType',
            field=models.CharField(choices=[(2, 'صوتی'), (1, 'تصویری')], max_length=1, verbose_name='Type of This Item'),
        ),
    ]
