# Generated by Django 2.2.13 on 2020-06-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_auto_20200630_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='itemType',
            field=models.CharField(choices=[('S', 'صوتی'), ('V', 'تصویری')], max_length=1, verbose_name='Type of This Item'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='ArchiveImages'),
        ),
    ]
