# Generated by Django 2.2.13 on 2020-07-26 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_auto_20200630_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
