# Generated by Django 2.2.13 on 2020-07-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_archive_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='time',
            new_name='addTime',
        ),
    ]
