# Generated by Django 2.2.13 on 2020-07-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0011_auto_20200726_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='src',
            field=models.FileField(default='default.mp4', upload_to='ArchiveFiles'),
            preserve_default=False,
        ),
    ]
