# Generated by Django 2.2.13 on 2020-07-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0012_archive_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='url',
            field=models.URLField(blank=True, default='http://172.16.13.207:1374', verbose_name='URL'),
        ),
    ]
