# Generated by Django 2.2.13 on 2020-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0013_auto_20200727_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='url',
            field=models.URLField(blank=True, default='http://172.16.13.207:8000', verbose_name='URL'),
        ),
    ]
