# Generated by Django 2.2.13 on 2020-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_auto_20200728_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='type',
            field=models.CharField(default='string', max_length=30),
            preserve_default=False,
        ),
    ]
