# Generated by Django 2.2.13 on 2020-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_setting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='altValue',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=500),
        ),
    ]
