# Generated by Django 2.2.13 on 2020-07-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0017_auto_20200728_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='desc1',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='desc2',
        ),
    ]
