# Generated by Django 2.2.13 on 2020-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0018_auto_20200729_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductoritem',
            name='duration',
            field=models.IntegerField(verbose_name='Program Duration'),
        ),
    ]
