# Generated by Django 2.2.13 on 2020-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0019_auto_20200730_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='duration',
            field=models.IntegerField(default='120', verbose_name='Duration of this item'),
        ),
    ]
