# Generated by Django 2.2.13 on 2020-08-10 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0021_auto_20200810_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='addTime',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
